// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"h68u-tiktok-app-microservice/services/3_contact/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/douyin/relation/friend/list",
				Handler: GetFriendListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/message/action",
				Handler: SendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/douyin/message/chat",
				Handler: GetHistoryMessageHandler(serverCtx),
			},
		},
	)
}
