// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterReply struct {
	BasicReply
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginReply struct {
	BasicReply
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type GetUserInfoRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type GetUserInfoReply struct {
	BasicReply
	User User `json:"user"`
}

type FollowRequest struct {
	Token      string `form:"token"`
	ToUserId   int64  `form:"to_user_id"`
	ActionType int64  `form:"action_type"`
}

type FollowReply struct {
	BasicReply
}

type FollowListRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FollowListReply struct {
	BasicReply
	Users []User `json:"user_list"`
}

type FansListRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FansListReply struct {
	BasicReply
	Users []User `json:"user_list"`
}

type BasicReply struct {
	Code int64  `json:"status_code"`
	Msg  string `json:"status_msg"`
}

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type Video struct {
	Id            int64  `json:"id"`
	Title         string `json:"title"`
	Author        User   `json:"author"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
}

type Comment struct {
	Id         int64  `json:"id"`
	Content    string `json:"content"`
	User       User   `json:"user"`
	CreateDate string `json:"create_date"`
}

type Message struct {
	Id         int64  `json:"id"`
	Content    string `json:"content"`
	CreateTime int64  `json:"create_time"`
	FromUserId int64  `json:"from_user_id"`
	ToUserId   int64  `json:"to_user_id"`
}

type GetVideoListRequest struct {
	LatestTime int64  `form:"latest_time,optional"`
	Token      string `form:"token,optional"`
}

type GetVideoListReply struct {
	BasicReply
	NextTime  int64   `json:"next_time"`
	VideoList []Video `json:"video_list"`
}

type PublishVideoRequest struct {
	Title string `form:"title"`
	Token string `form:"token"`
}

type PublishVideoReply struct {
	BasicReply
}

type PublishedListRequest struct {
	Token  string `form:"token"`
	UserId int64  `form:"user_id"`
}

type PublishedListReply struct {
	BasicReply
	VideoList []Video `json:"video_list"`
}

type FavoriteVideoRequest struct {
	VideoId    int64  `form:"video_id"`
	Token      string `form:"token"`
	ActionType int64  `form:"action_type"`
}

type FavoriteVideoReply struct {
	BasicReply
}

type FavoriteListRequest struct {
	Token  string `form:"token"`
	UserId int64  `form:"user_id"`
}

type FavoriteListReply struct {
	BasicReply
	VideoList []Video `json:"video_list"`
}

type CommentVideoRequest struct {
	VideoId    int64  `form:"video_id"`
	Token      string `form:"token"`
	ActionType int64  `form:"action_type"`
	Content    string `form:"comment_text"`
	CommentId  int64  `form:"comment_id,optional"`
}

type CommentVideoReply struct {
	BasicReply
	Comment Comment `json:"comment"`
}

type CommentListRequest struct {
	Token   string `form:"token"`
	VideoId int64  `form:"video_id"`
}

type CommentListReply struct {
	BasicReply
	CommentList []Comment `json:"comment_list"`
}

type GetFriendListRequest struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type GetFriendListReply struct {
	BasicReply
	FriendList []Friend `json:"user_list"` // 没错就是这个名字
}

type Friend struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
	Message       string `json:"message"`
	MsgType       int64  `json:"msgType"`
}

type SendMessageRequest struct {
	Token      string `from:"token"`
	ToUserId   int64  `from:"to_user_id"`
	Content    string `from:"content"`
	ActionType int64  `from:"action_type"`
}

type SendMessageReply struct {
	BasicReply
}

type GetHistoryMessageRequest struct {
	Token    string `form:"token"`
	ToUserId int64  `form:"to_user_id"`
}

type GetHistoryMessageReply struct {
	BasicReply
	MessageList []Message `json:"message_list"`
}
