// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"h68u-tiktok-app-microservice/services/1_user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/douyin/user/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/douyin/user",
					Handler: GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/relation/action",
					Handler: FollowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/follow/list",
					Handler: FollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/follower/list",
					Handler: FansListHandler(serverCtx),
				},
			}...,
		),
	)
}
