// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"h68u-tiktok-app-microservice/services/2_video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/douyin/feed",
				Handler: GetVideoListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/douyin/publish/action",
					Handler: PublishVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/publish/list",
					Handler: PublishedListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/favorite/action",
					Handler: FavoriteVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/favorite/list",
					Handler: FavoriteListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/comment/action",
					Handler: CommentVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/comment/list",
					Handler: CommentListHandler(serverCtx),
				},
			}...,
		),
	)
}
