// Code generated by goctl. DO NOT EDIT!
// Source: contact.proto

package contactclient

import (
	"context"

	"h68u-tiktok-app-microservice/service/rpc/contact/types/contact"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateMessageRequest     = contact.CreateMessageRequest
	Empty                    = contact.Empty
	GetLatestMessageRequest  = contact.GetLatestMessageRequest
	GetLatestMessageResponse = contact.GetLatestMessageResponse
	GetMessageListRequest    = contact.GetMessageListRequest
	GetMessageListResponse   = contact.GetMessageListResponse
	Message                  = contact.Message

	Contact interface {
		CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Empty, error)
		GetLatestMessage(ctx context.Context, in *GetLatestMessageRequest, opts ...grpc.CallOption) (*GetLatestMessageResponse, error)
		GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListResponse, error)
	}

	defaultContact struct {
		cli zrpc.Client
	}
)

func NewContact(cli zrpc.Client) Contact {
	return &defaultContact{
		cli: cli,
	}
}

func (m *defaultContact) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.CreateMessage(ctx, in, opts...)
}

func (m *defaultContact) GetLatestMessage(ctx context.Context, in *GetLatestMessageRequest, opts ...grpc.CallOption) (*GetLatestMessageResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.GetLatestMessage(ctx, in, opts...)
}

func (m *defaultContact) GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListResponse, error) {
	client := contact.NewContactClient(m.cli.Conn())
	return client.GetMessageList(ctx, in, opts...)
}
