// Code generated by goctl. DO NOT EDIT!
// Source: contact.proto

package server

import (
	"context"

	"h68u-tiktok-app-microservice/services/3_contact/rpc/internal/logic"
	"h68u-tiktok-app-microservice/services/3_contact/rpc/internal/svc"
	"h68u-tiktok-app-microservice/services/3_contact/rpc/types/contact"
)

type ContactServer struct {
	svcCtx *svc.ServiceContext
	contact.UnimplementedContactServer
}

func NewContactServer(svcCtx *svc.ServiceContext) *ContactServer {
	return &ContactServer{
		svcCtx: svcCtx,
	}
}

func (s *ContactServer) GetFriendsId(ctx context.Context, in *contact.GetFriendsIdRequest) (*contact.GetFriendsIdResponse, error) {
	l := logic.NewGetFriendsIdLogic(ctx, s.svcCtx)
	return l.GetFriendsId(in)
}

func (s *ContactServer) CreateMessage(ctx context.Context, in *contact.CreateMessageRequest) (*contact.Empty, error) {
	l := logic.NewCreateMessageLogic(ctx, s.svcCtx)
	return l.CreateMessage(in)
}

func (s *ContactServer) GetMessageList(ctx context.Context, in *contact.GetMessageListRequest) (*contact.GetMessageListResponse, error) {
	l := logic.NewGetMessageListLogic(ctx, s.svcCtx)
	return l.GetMessageList(in)
}
