// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id            int    `json:"id"`
	Name          string `json:"name"`
	FollowCount   int    `json:"follow_count"`
	FollowerCount int    `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type Message struct {
	Id         int    `json:"id"`
	Content    string `json:"content"`
	CreateTime string `json:"create_time"`
}

type GetFriendListRequest struct {
	UserId int    `json:"user_id"`
	Token  string `json:"token"`
}

type GetFriendListReply struct {
	Code     int    `json:"status_code"`
	Msg      string `json:"status_msg"`
	UserList []User `json:"user_list"`
}

type SendMessageRequest struct {
	Token      string `json:"token"`
	ToUserId   int    `json:"to_user_id"`
	Content    string `json:"content"`
	ActionType int    `json:"action_type"`
}

type SendMessageReply struct {
	Code int    `json:"status_code"`
	Msg  string `json:"status_msg"`
}

type GetHistoryMessageRequest struct {
	Token    string `json:"token"`
	ToUserId int    `json:"to_user_id"`
}

type GetHistoryMessageReply struct {
	Code        int       `json:"status_code"`
	Msg         string    `json:"status_msg"`
	MessageList []Message `json:"message_list"`
}
