name: build-rpc-contact

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-rpc-contact.yml'
      - 'service/rpc/contact/**'
      - 'common/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build-rpc-contact.yml'
      - 'service/rpc/contact/**'
      - 'common/**'

env:
  CONTAINER: rpc-contact

jobs:
  build-base:
    name: Build Base
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: registry.cn-hongkong.aliyuncs.com/h68u-tiktok-microservice/${{ env.CONTAINER }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: service/rpc/contact/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Webhook
        run: |
          curl '${{ secrets.WEBHOOK_URL }}&target=${{ env.CONTAINER }}'